# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Open PRs for ready tasks (independent or stacked) on the fork sandbox.

Usage:
    python open_mr.py <task-id>         # independent task → PR base = dev
    python open_mr.py --stacked <gid>   # group of tasks   → stacked PRs

Each PR is created via `_gh.py pr-create` (forced --repo feipeng1234/dimos),
then GitHub native auto-merge is enabled (squash). If auto-merge cannot be
enabled within the mergeable_state retry window, the task is marked
READY_FOR_MAINTAINER instead — never blocks waiting for a human to come back.
"""

from __future__ import annotations

import datetime as dt
import importlib.util
import json
from pathlib import Path
import subprocess
import sys

SCRIPTS = Path(__file__).resolve().parent
BOARD = SCRIPTS / "board.py"


def _load_gh():
    spec = importlib.util.spec_from_file_location("_gh", SCRIPTS / "_gh.py")
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load _gh.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_gh = _load_gh()


def _board(*args: str, capture: bool = True) -> tuple[int, str, str]:
    proc = subprocess.run(
        [sys.executable, str(BOARD), *args],
        capture_output=capture,
        text=True,
    )
    return proc.returncode, proc.stdout, proc.stderr


def _task_info(task_id: str) -> dict:
    rc, out, err = _board("task-info", task_id)
    if rc != 0:
        raise RuntimeError(f"task-info {task_id} failed: {err}")
    return json.loads(out)


def _group_info(group_id: str) -> dict:
    rc, out, err = _board("group-info", group_id)
    if rc != 0:
        raise RuntimeError(f"group-info {group_id} failed: {err}")
    return json.loads(out)


def _now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def _body_independent(task: dict) -> str:
    parts = [
        f"## {task['title']}",
        "",
        "**verifier summary**:",
        "",
        "```",
        task.get("feedback_summary") or "(verifier did not record a summary)",
        "```",
        "",
        "---",
        "Generated by `dimos-agentic-harness` v0.2 (fork sandbox).",
        "Conflict policy: rebase-and-regenerate. Bot reviews auto-resolved; human reviews escalate to implementer.",
    ]
    return "\n".join(parts)


def _body_stacked(task: dict, group_id: str, prev_pr_number: int | None) -> str:
    parts = [
        f"## {task['title']}",
        "",
        f"Part of stacked group `{group_id}`.",
    ]
    if prev_pr_number:
        parts.append(f"Depends on #{prev_pr_number}.")
    parts.extend(
        [
            "",
            "**verifier summary**:",
            "",
            "```",
            task.get("feedback_summary") or "(verifier did not record a summary)",
            "```",
            "",
            "---",
            "Generated by `dimos-agentic-harness` v0.2 (fork sandbox, stacked).",
        ]
    )
    return "\n".join(parts)


def _open_one_pr(task: dict, base: str, body: str) -> dict:
    """Push branch, open PR, attempt auto-merge, write board status. Returns final task record."""
    task_id = task["id"]
    branch = task["branch"]
    if not branch:
        raise RuntimeError(f"task {task_id} has no branch")

    print(f"[mr] pushing {branch}", file=sys.stderr)
    _gh.push_branch(branch, force=True)

    print(f"[mr] creating PR {branch} → {base}", file=sys.stderr)
    pr = _gh.pr_create(branch=branch, title=task["title"] or branch, body=body, base=base)
    pr_number = int(pr["number"])
    pr_url = pr.get("url") or ""

    _board(
        "set-status",
        task_id,
        "PR_OPEN",
        "--pr-url",
        pr_url,
        "--pr-number",
        str(pr_number),
        "--opened-at",
        _now_iso(),
    )

    print(f"[mr] PR #{pr_number} created; checking mergeable state (up to 30s)", file=sys.stderr)
    stable = _gh.pr_view_with_mergeable_retry(pr_number)
    review_decision = stable.get("reviewDecision") or ""
    mergeable = stable.get("mergeable") or "UNKNOWN"

    can_auto_merge = review_decision in ("", "APPROVED") and mergeable in (
        "MERGEABLE",
        "CONFLICTING",
        "UNKNOWN",
    )

    if not can_auto_merge:
        reason = f"reviewDecision={review_decision} mergeable={mergeable}"
        print(f"[mr] cannot enable auto-merge: {reason}", file=sys.stderr)
        _board(
            "set-status",
            task_id,
            "READY_FOR_MAINTAINER",
            "--ready-for-maintainer-reason",
            reason,
        )
        return _task_info(task_id)

    enabled = _gh.pr_enable_auto_merge(pr_number, method="squash")
    if not enabled:
        print(f"[mr] gh pr merge --auto rejected for #{pr_number}", file=sys.stderr)
        _board(
            "set-status",
            task_id,
            "READY_FOR_MAINTAINER",
            "--ready-for-maintainer-reason",
            "gh pr merge --auto rejected",
        )
        return _task_info(task_id)

    _board("set-status", task_id, "BABYSITTING")
    print(f"[mr] {task_id} → BABYSITTING (auto-merge armed)", file=sys.stderr)
    return _task_info(task_id)


def open_independent(task_id: str) -> int:
    task = _task_info(task_id)
    if task["status"] not in ("READY", "REVISING"):
        print(
            f"[mr] task {task_id} is in status {task['status']}; expected READY",
            file=sys.stderr,
        )
        return 2
    body = _body_independent(task)
    _open_one_pr(task, base="dev", body=body)
    return 0


def open_stacked(group_id: str) -> int:
    info = _group_info(group_id)
    if info.get("gate_status") != "PASSED":
        print(
            f"[mr] group {group_id} gate_status={info.get('gate_status')}; expected PASSED",
            file=sys.stderr,
        )
        return 2

    members_by_id = {m["id"]: m for m in info["members"]}
    topo = info["topo_order"]
    prev_branch = "dev"
    prev_pr_number: int | None = None

    for tid in topo:
        member_meta = members_by_id[tid]
        task = _task_info(tid)
        if task["status"] not in ("READY", "GROUP_GATE", "GROUP_WAIT"):
            print(
                f"[mr] member {tid} status {task['status']} — expected READY-ish",
                file=sys.stderr,
            )
            return 2
        body = _body_stacked(task, group_id, prev_pr_number)
        _board("set-status", tid, "STACKED_PR_OPEN")
        result = _open_one_pr(task, base=prev_branch, body=body)
        prev_pr_number = int(result["pr_number"]) if result.get("pr_number") else prev_pr_number
        prev_branch = member_meta["branch"]

    return 0


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__, file=sys.stderr)
        return 2
    if argv[0] == "--stacked":
        if len(argv) != 2:
            print("usage: open_mr.py --stacked <group-id>", file=sys.stderr)
            return 2
        return open_stacked(argv[1])
    if len(argv) != 1:
        print("usage: open_mr.py <task-id>", file=sys.stderr)
        return 2
    return open_independent(argv[0])


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
